org.gradle.jvmargs=-Xshare:off -Xmx700m -XX:MaxMetaspaceSize=180m -XX:+UseSerialGC
kotlin.daemon.jvm.options=-Xshare:off -Xmx500m -XX:MaxMetaspaceSize=150m -XX:+UseSerialGC
org.gradle.daemon=false
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true
android.suppressUnsupportedCompileSdk=35
